/*
SQLyog Enterprise - MySQL GUI v8.14 
MySQL - 5.6.16 : Database - task
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`task` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `task`;

/*Table structure for table `task` */

DROP TABLE IF EXISTS `TASK`;

CREATE TABLE `TASK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `UUID` varchar(128) DEFAULT NULL COMMENT '防重字段',
  `BIZ_ID` varchar(128) DEFAULT NULL COMMENT '业务流水号',
  `PARENT_ID` varchar(255) DEFAULT NULL COMMENT '父任务',
  `TASK_TYPE` smallint(5) DEFAULT NULL COMMENT '任务类型',
  `TASK_DATA` text COMMENT '任务数据',
  `TASK_STATUS` smallint(5) DEFAULT NULL COMMENT '任务状态',
  `RETRY_COUNT` smallint(5) DEFAULT NULL COMMENT '运行次数',
  `ERROR_MSG` text COMMENT '错误原因',
  `BIZ_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `RESULT_STATUS` smallint(5) DEFAULT NULL COMMENT '任务结果.0:表示任务初始,2:表示任务成功,1:表示任务失败',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `LAST_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_UUID` (`UUID`),
  KEY `IDX_TASKTYPE` (`TASK_TYPE`) USING BTREE,
  KEY `IDX_CREATETIME` (`CREATE_TIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务表';

/*Data for the table `task` */


/*Table structure for table `task_service_config` */

DROP TABLE IF EXISTS `TASK_SERVICE_CONFIG`;

CREATE TABLE `TASK_SERVICE_CONFIG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TASK_TYPE` int(11) NOT NULL COMMENT '任务类型',
  `TASK_TYPE_DESC` varchar(100) DEFAULT NULL COMMENT '任务类型描述',
  `TASK_SERVICE` varchar(100) DEFAULT NULL COMMENT 'serviceId',
  `TASK_PARENT_TYPE` int(11) DEFAULT NULL COMMENT '父任务类型',
  `STATUS` int(11) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_TASKTYPE` (`TASK_TYPE`) USING BTREE,
  UNIQUE KEY `UQ_TASKPARENTTYPE` (`TASK_PARENT_TYPE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `task_service_config` */


/*Table structure for table `timer_task_config` */

DROP TABLE IF EXISTS `TIMER_TASK_CONFIG`;

CREATE TABLE `TIMER_TASK_CONFIG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TASK_TIMER_TYPE` int(11) NOT NULL COMMENT '执行任务的类型',
  `TASK_TIMER_DESC` varchar(100) NOT NULL COMMENT '定时任务描述',
  `TASK_DATA` varchar(255) DEFAULT NULL COMMENT '生成任务数据JSON',
  `DATA_TYPE` varchar(100) DEFAULT NULL COMMENT '数据类型 month表示每月执行一次，day表示每天执行一次，hour表示每小时执行一次,minute表示每分钟执行',
  `YEAR` int(11) DEFAULT NULL,
  `MONTH` int(11) DEFAULT NULL,
  `DAY` int(11) DEFAULT NULL,
  `HOUR` int(11) DEFAULT NULL,
  `MINUTE` int(11) DEFAULT NULL,
  `SECOND` int(11) DEFAULT NULL,
  `BIZ_TIME` datetime DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL COMMENT '任务状态。0:停止，1:启动',
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `Q_TASKTIMERTYPE` (`TASK_TIMER_TYPE`) USING BTREE,
  UNIQUE KEY `Q_TYPE_PARENTTYPE` (`TASK_TIMER_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `timer_task_config` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
